# generate示例配置
logging:
  level: error
streams:
  - input:
      type: "generate"
      context: '{ "timestamp": 1625000000000, "value": 10, "sensor": "temp_1" }'
      interval: 1ms
      batch_size: 10000


    pipeline:
      thread_num: 4
      processors:
#        - type: "batch"
#          count: 3
#          timeout_ms: 10000
#          data_type: "binary"
        - type: "json_to_arrow"

        - type: "sql"
          # SQL查询语句，支持标准SQL语法
          query: "SELECT count(*) FROM flow WHERE value >= 10 group by sensor"
        - type: "arrow_to_json"


    output:
      type: "stdout"
